extends Node

var phrases = [
	[["Oh, these 3 worn words",
	"that we whisper like the rubbing hands",
	"Of tourists in Verona",
	"I just want to love you in my own language"],
	"alt-J", "3WW",
	"https://youtu.be/ZwBkXgWNs_M?t=247"],
	
	[["It's only music",
	"Did you want it to be food for the soul?",
	"It's only music",
	"Did you think it would heal and help you unfold?"],
	"Lucy Swann", "Barely Dancing",
	"https://youtu.be/OQy7sTDzz70?t=8"],
	
	[["I feel like a pole without a sign",
	"How dare you say I feel just fine",
	"It's been 2 years, should I tell you now",
	"What a mess you've left me, why?"],
	"Monoral", "Healthy Sick Bastard",
	"https://youtu.be/vRqzbN7RPfM?t=40"],
	
	[["Don't oversleep no time for dreamin' my son",
	"Childhood is over, now the real game may begin",
	"Where you can loose don't even try to win"],
	"Nasser", "Bronson",
	"https://youtu.be/DyTmHTamp2o?t=5"],

	[["So can you understand",
	"Why I want a daughter while I'm still young?",
	"I want to hold her hand",
	"Show her some beauty, before the damage is done",
	"But if it's too much to ask",
	"Then send me a son"],
	"Mr Little Jeans (original by Arcade Fire)", "The Suburbs",
	"https://youtu.be/-n6NRcz53_8?t=171"],

	[["In time or so I'm told",
	"I'm just another soul for sale, oh well",
	"This page is out of print",
	"We are not permanent, we're temporary, temporary",
	"Same old story"],
	"Infected Mushroom (original by Foo Fighters)", "The Pretender",
	"https://youtu.be/_oAutLYMOgk?t=143"],
	
	[["You are the most fortunate one",
	"No reason to believe",
	"You have the arms to sound the alarm",
	"But you don't feel the need"],
	"Son Lux", "I Am The Others",
	"https://youtu.be/KRjEgozxdqw?t=36"],

	[["When you were young, you were numb",
	"You felt like nothing, you felt like no one",
	"What you wanted was to belong",
	"As time went by, did you love someone?"],
	"Pale Honey", "The Heaviest Of Storms (Devotion, Pt. 1)",
	"https://youtu.be/MdwPU-5M1Gw?t=33"],

	[["Send for help",
	"I've been trapped inside my head",
	"For days",
	"Take a rest",
	"You've been running through my veins",
	"For days"],
	"Gold Key", "Creep In Slowly",
	"https://youtu.be/zuSEERcptPs?t=32"],
	
	[["Crawling on the floor all around this space",
	"Talking to myself, what is this thing I gotta face?",
	"Walking through a door, has it been a waste?",
	"Going on and on, thinking I could find my place"],
	"Korn", "Starting Over", 
	"https://youtu.be/bDhano3TuP4?t=69"],

	[["You've had enough of the road",
	"That was laid along beside you",
	"Like a lover meant for another bed",
	"And so you left in the morning",
	"And all that's left behind you",
	"Are the fading frames that you've got instead"],
	"Yppah (ft. Anomie Belle)", "Film Burn",
	"https://youtu.be/Nmr3DEiNc0k?t=38"],

	[["Painkillers, cough syrup",
	"Sleeping pills, bottle of schnapps",
	"Sink your teeth, chew it up",
	"Take a knife, make a clean cut",
	"Roast the flesh, medium heat",
	"Add garlic, pepper and salt",
	"Meat is too tough to eat",
	"So I'll feed it to the dog"],
	"SKYND", "Armin Meiwes",
	"https://youtu.be/3Z6LT8iA_0c?t=90"],

	[["Through the glass I'm dilated",
	"I need a change in the weather too, but",
	"I been talked around the town",
	"But I'm not sorry for nobody"],
	"Public Memory", "Epigone",
	"https://youtu.be/i2XIezx3IZo?t=16"],

	[["My zef accent is very foreign",
	'When I speak overseas they go "I beg your pardon?"',
	"You can't get me, like Eric Cartman",
	'Naughty little kitty go "meow"',
	"Yes daddy, I'm a big girl now",
	'Jas little devil make your dick go "wow!"',
	"Yeah, boy, Yo-Landi Vi$$er is hot stuff"],
	"Die Antwoord", "Cookie Thumper!",
	"https://youtu.be/K8nrF5aXPlQ?t=174"],

	[["Worship the screen, cocksucker lies",
	"There's a stream of middle-class hypocrisy tonight",
	"Every time we beg for the rich man to provide",
	"There's countries to be conquered, people to divide"],
	"IAMX", "Oh Cruel Darkness Embrace Me",
	"https://youtu.be/IJMmkAlx0lI?t=38"],

	[["Give me a drug and I'll take it",
	"Watching you sharpen knives",
	"You give me hell but I'll make it",
	"I've still got one good eye",
	"Blind as a fool, I can fake it",
	"Telling the truth with lies",
	"It won't be long 'til I break it",
	"You weigh me, you weigh me down"],
	"Lorn", "Weigh Me Down",
	"https://youtu.be/UEBIsUsvheA?t=100"],

	[["If only I could feel nothing",
	"Hollow as a bell",
	"I can hear my own heart ringing sometimes",
	"Singing clear and empty",
	"A perfect vessel, a sweet lord",
	"Instead, now, full and fragile",
	"A bloody mess beating away"],
	"Lapalux (ft. Louisahhh)", "Rotted Arp",
	"https://youtu.be/NBJTywsyiO4?t=21"],
	
	[["Stand up",
	"You've got to manage",
	"I won't sympathize anymore",
	"And if you complain once more",
	"You'll meet an army of me"],
	"The Great Discord (original by Björk)", "Army Of Me",
	"https://youtu.be/1SzyOdM_oYM?t=30"],

	[["Take that old girlfriend",
	"Set her hair on fire",
	"Watch her start screaming",
	"And running for the water",
	"Gonna take that old apartment",
	"Set that place on fire",
	"Gonna leave the world at large and",
	"Run back to the wild"],
	"Mother Mother", "To The Wild",
	"https://youtu.be/IkGHqHG-M68?t=126"],
	
	[["When the moon is full, and I've pried",
	"I'll take up your guts to the little shed outside",
	"I'll shuck all the light from my skin then I'll hide it in you",
	"I'll pluck the long grass",
	"That grows from me and hide it (in you)"],
	"Purity Ring", "shuck",
	"https://www.youtube.com/watch?v=8dWIImvvSVs"],

	[["And all you see is dark and vague",
	"And all you feel is life unmade",
	"And all your hopes just bleed away",
	"And all you are is lost and fades"], 
	"Gary Numan", "Here In The Black",
	"https://youtu.be/kbQuq3GeFIs?t=239"],

	[["If I can hold you tonight",
	"And keep you so safe armor falls aside",
	"If I can hold, baby, you tonight",
	"I doubt it's going to change what we are inside"],
	"Battle Tapes", "Last Resort & Spa",
	"https://youtu.be/fCya1_jvPgo?t=188"],

	[["Oh, how beautiful",
	"How soothing, oh",
	"That everything is as it is",
	"Sometimes I wish I was like that too"],
	"Sevdaliza", "Voodoov",
	"https://youtu.be/UyVxQl1-EKk?t=131"],
	
	[["Counterfeit hypocrite",
	"Runs them all, runs them all",
	"Seething ill 'cause they will",
	"Counting coins, counting stem cells",
	"Wiretap turbidity, human laboratory",
	"Kill the squid, cut the tree",
	"Arrogant human meat"],
	"King Gizzard & The Lizard Wizard", "Organ Farmer",
	"https://youtu.be/Qskg6yvn8vc?t=95"],
	
	[["The me that you know,",
	"(s)he used to have feelings",
	"But the blood has stopped pumping and (s)he is left to decay",
	"The me that you know is now made up of wires",
	"And even when I'm right with you, I'm so far away"],
	"Oraclez (original by Nine Inch Nails)", "The Becoming",
	"https://youtu.be/KG2YS7fEuPs?t=101"],
	
	[["Surrender to the mud, your body's given up",
	"Lay down and stop this run, there's nothing left to love",
	"Watching you slowly sink in, dirty water dissolving your skin",
	"As it cleanses your sins, the ground is swallowing"],
	"Deja Vu", "Soil",
	"https://youtu.be/rdbE8AKmFVs?t=208"],
	
	[["Avada Kedavra, I speak to destroy",
	"The feelings I have, I cannot avoid",
	"Through twisted tongues, a hex deployed on you",
	"That all the pretties in your bed",
	"Escape your hands and make you sad",
	"And all the things you wish you had you'd lose"],
	"Bambie Thug", "Doomsday Blue",
	"https://youtu.be/ZGRXRrlIspY?t=17"],
	
	[["On my little waters darker than the sea",
	"Master of all my feelings",
	"Please protect me",
	"I will arise with or without what's me",
	"Life won't tread on me, life won't keep me still"],
	"Precious Child", "My Little Problem (Violet Door)",
	"https://youtu.be/W_t23ck0xsw?t=32"],
	
	[["If I could be anyone, I'd be a dog lying next to you",
	"And it's not a perfect world",
	"You know that's gone, me too",
	"But if you run with me, I'd keep you safe and sound"],
	"Niteppl", "High With You",
	"https://youtu.be/ZVbM5OzOMH4?t=92"],
	
	[["I don't know where my head is",
	"Something's missing in my chest, I think I need a medic",
	"I been looking for a flaw in you, I don't really get it",
	"You don't even know you're flawless, it's giving me a headache"],
	"Asal", "Headache",
	"https://youtu.be/F3oV5PqFWHc?t=47"],
	
	[["Annie, won't you come and meet me",
	"Where the neon lights are shining?",
	"Annie, won't you dance behind me?",
	"Don't give up, let music save you",
	"Annie, have you ever felt the need",
	"Of someone else to see you?",
	"Annie, come here, don't you worry",
	"We are here for you to lean on"],
	"Röyksopp (ft. Lykke Li)", "Were You Ever Wanted",
	"https://youtu.be/oJVSXVvXb60?t=91"],
	
	[["Did someone whisper?",
	"I'm really not so sure",
	"I could've been asleep",
	"Is everyone this frightened?",
	"Are there more like me?",
	"There's just got to be"],
	"Tweaker", "Linoleum",
	"https://youtu.be/7K9JTj7oRXQ?t=177"],
	
	[["Infants in infantry, rewrite their history",
	"Uproot their colony, you're ripe for harvesting",
	"Virgin cells to penetrate, too premature to permeate",
	"They can't elucidate",
	"Never thought I was the enemy",
	"I am the plague"],
	"Crystal Castles", "Plague",
	"https://youtu.be/cx2lJIOTBjs?t=66"],
	
	[["They've started selling it in cans, now you can save on flights",
	"Have a tipple on your lunch break and have revelations at your desk",
	"Hopes and aspirations can be altered chemically",
	"And with a renewed sense of purpose you can finish that report by 3",
	"But I don't want to know the truth about myself",
	"Amazona, turn me into someone else"],
	"The Vanity Project", "Conquistador", 
	"https://youtu.be/9B1WVufAjGM?t=85"],
	
	[["I wanna help you",
	"I can save you some time",
	"I wanna take care of you, let me ease your mind",
	"I came to do a job today",
	"Not here to laugh, not here to play",
	"It's serious, it's not a game",
	"I'm at your service, baby"],
	"Big Data", "Put Me To Work", 
	"https://youtu.be/hVmbWMS3W4I?t=16"],
	
	[["No way to stop, my brain will end up frying", 
	"Will fall apart before I could start crying",
	"It's now way too late to find the place to go",
	"I know there is no place to hide"],
	"Monikaze", "Mind Bubble",
	"https://youtu.be/y7-AbblztLM?t=90"],
	
	[["Feuer und Wasser kommt nicht zusammen",
	"Kann man nicht binden sind nicht verwandt",
	"In funken versunken steh ich in flammen",
	"Und bin im Wasser verbrannt"],
	"Rammstein", "Feuer Und Wasser",
	"https://youtu.be/XemxFo2X_JY?t=143"],
	
	[["Tabaką kramto, vaikų neturi",
	"Maitinas šukom ir kvapniu dangum",
	"Vartoja gamtą, į miestą žiūri",
	"Galvoja, mąsto, kaip tapti tuo žmogum padangėj"],
	"Solo Ansamblis", "Oro Balionu",
	"https://youtu.be/z7OhLjsuYXA?t=117"],
	
	[["Я поднимаю тяжёлые веки",
	"Я смотрю вверх, в серое небо",
	"Но вместо неба серая плита",
	"Она падает вниз и раздавит меня"],
	"IC3PEAK", "Hey",
	"https://youtu.be/nULmCwYcWwk?t=27"],
	
	[["It's an impossible dream but you realise",
	"You're not waking up",
	"Watch as the silence and protest fails us",
	"Higher than reason and brighter than light",
	"Gravity no longer wins",
	"It's an impossible thought, so you theorise",
	"This is what the resurrection feels like from the other side"],
	"Son Lux", "Ressurection",
	"https://youtu.be/AtEYqxF8aEg?t=12"],
	
	
	[["At the moment of creation",
	"When everything was just energy",
	"There was a process set in motion",
	"To bring you to me",
	"Just as close as you can be"],
	"Dan Warren", "Come Closer",
	"https://youtu.be/CZ7WXDMldMs?t=117"],
	
	[["Have we taken all we're good for?",
	"Have we registered our love in vain",
	"A church is not for praying",
	"It's for celebrating the life that bleeds through the pain",
	"It's for celebrating the life that shines through your veins",
	"How do you do it?"],
	"Hot Chip", "How Do You Do?",
	"https://youtu.be/zd_JW73R1Wk?t=120"],
	
	[["My feet are planted low",
	"Down in here in the shadow of you",
	"You've become a danger to me",
	"But from down here, I see",
	"That you are a liar",
	"Dripping with fire"],
	"Chaos Chaos", "Dripping With Fire",
	"https://youtu.be/MMFmeVeqFUY?t=92"],
	
	[["Last night all black and white",
	"When I was sleeping",
	"I felt shadows and emptiness surround me",
	"Just keep telling myself to live my life alive",
	"Like everything else",
	"Just keep on breathing and live"],
	"STRFKR", "While I'm Alive",
	"https://youtu.be/VoX9WIM6OoY?t=45"],
	
	[["I've been always playing solid as I'm waving",
	"So I became a liar, I've been underrating, overestimated",
	"I made it really hard for you to love me",
	"But there's so many things we could do",
	"And all we need is escaping",
	"So let's go back to our cocoon on the blackened afternoon",
	"I see your heart is bleeding too",
	"Let me bleed instead of you"],
	"Mily Chance", "Cocoon",
	"https://youtu.be/ernVvrYH9vg?t=135"],
	
	[["Lysergic feelings, I'm breathing barium vibes",
	"I'm looking down from the ceiling, I've got a bird's eye",
	"I'm in the bathtub swimming in lavender hymns",
	"I'm discovering God and she is paper-thin",
	"The question's loaded, am I naive?",
	"I had a vision of you watching me as I was fading in and out",
	"In a department store",
	"I don't want to be alone anymore"],
	"Sir Sly", "Astronaut",
	"https://youtu.be/_zECkdXSNoI?t=64"],
	
	[["We are young and we live fast",
	"Always dealing with the past",
	"We are all lost in a crowd",
	"We don't have time to be screwed",
	"Some of us born between the cracks",
	"Never finding the right path",
	"Weighed down with concrete blocks",
	"We are all on the same track"],
	"Concorde", "Sons",
	"https://youtu.be/ZeBrnuQxEsQ?t=28"],
	
	[["For our only hope is falling in love",
	"With who we are and what we wanna do",
	"Is it gonna be you? Is it gonna be me?",
	"Well, something's gotta happen",
	"Or we'll be on our knees"],
	"Konoba (ft. R.O)", "On Our Knees",
	"https://youtu.be/pvT7mDwZ7Hw?t=35"],
	
	[["Have you ever had the feeling",
	"When you just don't wanna breath",
	"And you can't stand up without leaning",
	"And there's nothing to believe in?",
	"Have you ever walked outside",
	"And felt like you might throw up right beside your car",
	"Before you even get inside?",
	"Every day of my, day of my, day of my life!"],
	"Elohim", "Xanax",
	"https://youtu.be/MZcqj0aasWo?t=38"],
	
	[["Waiting in the car",
	"Waiting for the ride in the dark",
	"Drinking in the lounge",
	"Following the neon signs",
	"Waiting for a word",
	"Looking at the milky skyline",
	"The city is my church",
	"It wraps me in its blinding twilight"],
	"M83", "Midnight City",
	"https://youtu.be/dX3k_QDnzHE?t=74"],
]
